#spring:
#  data:
#    rest:
#      base-path: /api
#  hateoas:
#    use-hal-as-default-json-media-type: true
#  resources:
#    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
#  mvc:
#    static-path-pattern: /resources/**

#springdoc swagger
springdoc:
  swagger-ui:
    path: restapi.html

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.37.88.88:3306/HotPlaceMap
    username: root
    password: 19980530
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true



